---
# disable repos tasks file for ansible-role-spacewalk-client

- name: find original repo files
  find:
    paths: '/etc/yum.repos.d'
    patterns: '*.repo'
    use_regex: no
    recurse: no
  register: old_repo

- name: move original repos as *.old
  command: 'mv "{{ item }}" "{{ item }}.old"'
  with_items: '{{ old_repo.files }}'
