---
# enabble repo proxy tasks file for ansible-role-spacewalk-client

- name: add proxy to yum
  become: true
  lineinfile:
    dest: /etc/yum.conf
    line: 'proxy={{ spacewalk_client_proxy_yum_url }}'
    regexp: '^[ \t]*proxy[ \t]*=[ \t]*.*'
    insertafter: '.*distroverpkg.*'
  when: spacewalk_client_proxy_yum_url | length > 0
  tags:
    - yum_proxy

- block:
  - name: add proxy username to yum
    become: true
    lineinfile:
      dest: /etc/yum.conf
      line: 'proxy_username={{ spacewalk_client_proxy_yum_username }}'
      regexp: '^[ \t]*proxy_username[ \t]*=[ \t]*.*'
      insertafter: '^[ \t]*proxy[ \t]*=[ \t]*.*'
    tags:
      - yum_proxy

  - name: add proxy password to yum
    become: true
    lineinfile:
      dest: /etc/yum.conf
      line: 'proxy_password={{ spacewalk_client_proxy_yum_password }}'
      regexp: '^[ \t]*proxy_password[ \t]*=[ \t]*.*'
      insertafter: '^[ \t]*proxy[ \t]*=[ \t]*.*'
    tags:
      - yum_proxy
  when: spacewalk_client_proxy_yum_username | length > 0
