---
# spacewalk client register tasks file for ansible-role-spacewalk-client

- name: install Spacewalk client
  become: true
  package:
    name: '{{ spacewalk_client_download_dir }}/{{ spacewalk_client_download_file }}'
    state: present

- name: install packages
  become: true
  package:
    name: '{{ spacewalk_client_pacakges }}'
    state: present

- name: register to spacewalk server
  become: true # noqa 301 305
  become_user: '{{ spacewalk_client_root_user }}'
  shell: >
    rhnreg_ks --serverUrl={{ spacewalk_client_server_url }} --sslCACert={{ spacewalk_client_ca_cert_path }} \
     --activationkey={{ spacewalk_client_activation_key }}
  ignore_errors: yes
  no_log: false
  notify: restart spacewalk service
  when: not spacewalk_client_force_client_install

- name: force register to spacewalk server
  become: true # noqa 301 305
  become_user: '{{ spacewalk_client_root_user }}'
  shell: >
    rhnreg_ks --serverUrl={{ spacewalk_client_server_url }} --sslCACert={{ spacewalk_client_ca_cert_path }} \
     --activationkey={{ spacewalk_client_activation_key }} --force
  ignore_errors: yes
  no_log: false
  notify: restart spacewalk service
  when: spacewalk_client_force_client_install

#- name: enable Spacewalk subscription
#  become: true
#  become_user: '{{ spacewalk_client_root_user }}'
#  shell: >
#    rhn-actions-control --enable-all
#  args:
#    creates: 'valami'
#  no_log: false
#  notify: restart spacewalk service
