---
# handlers file for ansible-role-spacewalk-client

- name: restart spacewalk client
  service:
    name: '{{ spacewalk_client_service_name }}'
    state: '{{ spacewalk_client_service_status }}'
    enabled: '{{ spacewalk_client_service_enabled }}'
  listen: 'restart spacewalk service'
